### ISSUE TITLE
LOL I bought this now it's free

### ISSUE THREAD

**Issue by XMVZ** [itschasa/Discord-Backup#1]
Lit thank you for releasing source tho forreal :)

**Comment by itschasa** [comment]
lmao np, if you have any issues or suggestions, feel free to make an issue!

**Comment by cipherwithadot** [comment]
this doesn't look the same as https://www.youtube.com/watch?v=zXS4-_hTri0

and i'm disappointed but i think that doesn't matter because the source is public.

**Comment by itschasa** [comment]
this version has a better code base and cleaner console in my opinion

**Comment by cipherwithadot** [comment]
cool
