### ISSUE TITLE
what

### ISSUE THREAD

**Issue by CodeByAidan** [itschasa/Discord-Backup#11]
![image](https://user-images.githubusercontent.com/67598470/229642651-686ba83d-42e8-46b0-8def-b45c159b1898.png)
excuse me sir, i input number 3.14 and its no work?

**Comment by itschasa** [comment]
mb sir, you need to enter a number between 1 and 4, and it has to be a whole number (no decimals, or full stops)

**Comment by CodeByAidan** [comment]
bro seriously men? I dont even know how to count and you telling me I can't put option 3.14 or the word "hello world" in? smh 1/10
