### ISSUE TITLE
Restore object has no attribute 

### ISSUE THREAD

**Issue by AlphaTxch** [itschasa/Discord-Backup#12]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/65458669/231170798-f2518929-a8ae-4841-a22a-4d18c389068e.png">

**Comment by itschasa** [comment]
ill look into it, will probably be fixed in v2.0

**Comment by itschasa** [comment]
found the source, update soon

**Comment by itschasa** [comment]
fixed in v1.2.1
