### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vulnash** [itschasa/Discord-Backup#13]
Traceback (most recent call last):
  File "D:\Backup acc discord\cc\main.py", line 99, in <module>
    bkup = backup.backup(token_info[0], c, clnt.version)
  File "D:\Backup acc discord\cc\backup.py", line 38, in __init__
    f = open(f"backups\\{self.user_me['username']}#{self.user_me['discriminator']} @ {datetime.utcfromtimestamp(int(time.time())).strftime('%Y-%m-%d %H-%M-%S')}.bkup", "w", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'backups\\.....#0000 @ 2023-04-25 00-39-57.bkup'

**Comment by itschasa** [comment]
seems like an issue where the file doesnt exist on your system
