### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by itschasa** [itschasa/Discord-Backup#14]
I am aware of the issue, **this issue only affects the restoring capability.**
A fix will be released in v2.0 of this program, so please be patient.

This program has gotten more attention then I thought it would, so I feel like I should do it justice and recode the tool, making it more stable and fixable if any more issues arise.

Thank you <3

![image](https://github.com/itschasa/Discord-Backup/assets/79016507/470db943-74aa-433c-8e2a-53a372245574)

**Comment by itschasa** [comment]
fixed in v1.2.1

**Comment by zer0xtech** [comment]
ty man
