### ISSUE TITLE
Add guild backups (roles/channels)

### ISSUE THREAD

**Issue by sewrs12** [itschasa/Discord-Backup#16]
Can  we please get a Server-Backup version of this which backups all the server/roles/categories anything on that server and saves them to folder. So you can restore your old server settings etc when your server gets termed.

**Comment by itschasa** [comment]
This is a possibility, but there are a lot of scripts already available which has this functionability.

**Comment by Ranini** [comment]
can i have a link of this specified script

**Comment by itschasa** [comment]
> can i have a link of this specified script

just search on github for "discord server backup"
