### ISSUE TITLE
Add authorized apps backup

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [itschasa/Discord-Backup#18]
add a feature to list the names of all authorized apps on ur account

**Comment by itschasa** [comment]
can i ask how this would be useful to users?

**Comment by EasyAntiCheatSoftware** [comment]
> can i ask how this would be useful to users?

not the most useful thing, but if you want to re authorize some specific apps then u can do it from the backup

**Comment by itschasa** [comment]
i'll see what data discord returns from the endpoint, and see if it's possible to reconstruct the authorisation url. it probably won't be (for example the redirect query probably won't be there), but i'll look into it.

**Comment by itschasa** [comment]
the data on authorized apps comes from the endpoint:
`https://discord.com/api/v9/oauth2/tokens`
![image](https://github.com/itschasa/Discord-Backup/assets/79016507/c3dd748b-179c-4f05-a434-af9a8583cbc9)

only one thing is missing to reconstruct the verify url, and thats the redirect url:
```
https://discord.com/api/oauth2/authorize
    ?client_id={{ data['id'] }}
    &redirect_uri={{ _missing_ }}
    &response_type=code
    &scope={{ "%20".join(data['scopes']) }}
```

`https://discord.com/api/v9/applications/{{ app_id }}` does return the redirect_uris, but it also requires appropriate authentication (the discord account that made the application (aka no one using this tool))


therefore, i personally dont think that its worth adding authorized apps to the tool, as there's no real way of restoring them easily.
