### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by FuckingToasters** [itschasa/Discord-Backup#19]
Hello, it seems to me that itonly works for windows (it uses winddl lib) would be nice if you could also make it work for linux (by using os.name checks for example)

**Comment by itschasa** [comment]
backing up and restoring should work on linux
auto-backup and fetching your token automatically might not work on linux with this version
and also the os.system('cls') wont work ofc
i can add fetching the token automatically, but im not sure about auto-backup

**Comment by FuckingToasters** [comment]
Well I wasn't able to run it on Linux due to a ein32dll import, this libary is for windows only so I couldn't jnstall.it on my system which resulted in an module not found error.

**Comment by itschasa** [comment]
that library should only be triggered to import if you choose to scan for tokens
can you try without scanning to see if you can still use the tool?

**Comment by FuckingToasters** [comment]
> that library should only be triggered to import if you choose to scan for tokens can you try without scanning to see if you can still use the tool?

It happen directly after i start it, i can't even come to an menu where i can select anything

**Comment by itschasa** [comment]
can you send the error you receive?
