### ISSUE TITLE
Relationships are not restored if using old backup data with a new version

### ISSUE THREAD

**Issue by zer0xtech** [itschasa/Discord-Backup#22]
I dont know if its a bug or something when i weeks ago i created a backup of my main using the 1.2.1 version and today when i used it, i downloaded the 1.2.3 since update etc and i started restored servers and stuff worked perfectly except for the relations. It sent me all my relationships in the backup server but did not send any friend request.

Just wanted to let you know about this, no idea if it can help but yea also congrats for your tool its really cool, lmk if there is any way to tip or something

**Comment by ghost** [comment]
It is supposed to do that.

**Comment by itschasa** [comment]
> It sent me all my relationships in the backup server but did not send any friend request.

This is expected behaviour. You add each friend back manually, to prevent Discord giving the program Captchas, which it can't deal with/solve.
