### ISSUE TITLE
I mean this is clearly a virus...

### ISSUE THREAD

**Issue by W1IQ** [itschasa/Discord-Backup#3]
You have got Plague Stealer, Clip Banker, DiscordNitroMiner all binded into this file

Then you have about 15 files dropped onto the victims computer 

Any People Who Have Ran This File Please Do "WINDOWSKEY + R" then type "%temp%" and then do "CTRL + A" and then "DELETE"

You Also Should Run This In A VirtualMachine or A Sandbox (sandbox's can be bypassed so i reccomend a VirtualMachine)

**Comment by cipherwithadot** [comment]
:O

**Comment by itschasa** [comment]
> You have got Plague Stealer, Clip Banker, DiscordNitroMiner all binded into this file

i mean, its not any of these. if you are talking about the `fetch_tokens.py` file, then its used to fetch tokens so you dont have to enter the token manually. read through the source and all the imports before making ridiculous claims.


> Any People Who Have Ran This File Please Do "WINDOWSKEY + R" then type "%temp%" and then do "CTRL + A" and then "DELETE"

so your advice for people who have been infected with malware is to clear all temporary files?


> You Also Should Run This In A VirtualMachine or A Sandbox (sandbox's can be bypassed so i reccomend a VirtualMachine)

i never said you couldn't, feel free to use a vm or sandboxie.

**Comment by itschasa** [comment]
if you have any actual proof or criticism, feel free to reply to this thread or contact me on socials

**Comment by cipherwithadot** [comment]
:OO

**Comment by CodeByAidan** [comment]
bump %100 virus, totally. entire computer just fucking blew up, c'mon man 😢 

am broke men from somalia

**Comment by itschasa** [comment]
real
