### ISSUE TITLE
Crypto.cipher requirement

### ISSUE THREAD

**Issue by xHERMIS** [itschasa/Discord-Backup#31]
![image](https://github.com/itschasa/Discord-Backup/assets/104696522/65ded899-817b-43d6-a317-6742f44bf722)
Why would a 'Discord backup tool' need 'Crypto.cipher' package for backup and restore discord account ?

**Comment by itschasa** [comment]
it's used to fetch tokens from your machine automatically. if you don't want that, say "n" to fetch tokens
