### ISSUE TITLE
Trojan LMAO

### ISSUE THREAD

**Issue by ghost** [itschasa/Discord-Backup#38]
Hmm, fetches token by it self on the windows release and saves 2 little exe files in the temp folder nice lmaooooooo

**Comment by itschasa** [comment]
Duplicate of #24

As you can see here, it does not fetch the token without either:
1) explicit consent from the user when the program is run non-autonomously

https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L134-L137

https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L215-L218

2) asking the user when setting the program to run on startup

https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L255-L260

https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L115-L119


as for the "little exe files", this could be another piece of software doing that? the releases are built using a simple pyinstaller command, and no additional code is added to the source. feel free to build the exe from source yourself, or simply use the source instead.

**Comment by ghost** [comment]
> Duplicate of #24
> 
> As you can see here, it does not fetch the token without either:
> 
> 1. explicit consent from the user when the program is run non-autonomously
> 
> https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L134-L137
> 
> https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L215-L218
> 
> 2. asking the user when setting the program to run on startup
> 
> https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L255-L260
> 
> https://github.com/itschasa/Discord-Backup/blob/759fd56c3f52862a7d73c57bb68f4c729f02a0aa/main.py#L115-L119
> 
> as for the "little exe files", this could be another piece of software doing that? the releases are built using a simple pyinstaller command, and no additional code is added to the source. feel free to build the exe from source yourself, or simply use the source instead.

I am aware of the source being that but the release version seems to be doing this (the compiled version)

**Comment by itschasa** [comment]
> I am aware of the source being that but the release version seems to be doing this (the compiled version)

I'm not sure what you mean, if you don't want to use the release version because you're concerned, either build it from source yourself, or use the source code.
