### ISSUE TITLE
Add friends and dm backup 

### ISSUE THREAD

**Issue by taubensuppe** [itschasa/Discord-Backup#4]
Would be cool if it automatically saves the people’s k had contact with so username and tag

**Comment by itschasa** [comment]
can you reword that?

**Comment by itschasa** [comment]
@taubensuppe

**Comment by Scripped** [comment]
i think they're asking for a feature that saves usernames and tags (USERNAME#0000) of their friends and people they have dmed in the past. not sure though @taubensuppe

**Comment by marcus-alicia** [comment]
Yeah, what he wants is to save all names of open DMs, even if its not friends.

**Comment by itschasa** [comment]
sounds like a good idea, i'll add it soon

**Comment by itschasa** [comment]
Added in Release v1.1.0

Let me know of any suggestions/issues!
